## Tutorial Básico de Python

In [3]:
def suma(x: int, y: int) -> int:
    """Esta función suma dos números"""
    return x+y

In [2]:
suma(1,2)

3

In [6]:
class Persona:
    def __init__(self, nombre: str):
        self.nombre = nombre
    def hablar(self, msg: str):
        print(f"La persona {self.nombre} ha dicho: {msg}")
        

In [10]:
ricardo = Persona("Ricardo")
ricardo.hablar("Desconozco como funciona el método fit")
ricardo.nombre

La persona Ricardo ha dicho: Desconozco como funciona el método fit


'Ricardo'

In [11]:
traduccion = {
    "Inglés": "English",
    "Español": "Spanish",
    "Manzana": "Apple"
}

In [13]:
traduccion["Inglés"]

'English'

In [17]:
import torch
import torch.nn as nn
import torch.optim as optim

# Definir un modelo simple
class SimpleModel(nn.Module):
    def __init__(self):
        super(SimpleModel, self).__init__()
        self.fc1 = nn.Linear(10, 5)
        self.dropout = nn.Dropout(p=0.5)  # Dropout del 50%

    def forward(self, x):
        return self.dropout(self.fc1(x))

model = SimpleModel()
x = torch.randn(1, 10)
print(x)

model.train()
print(model(x))  # Dropout está activado (algunos valores pueden ser 0)

model.eval()
print(model(x))  # Dropout está desactivado (la salida es estable)

tensor([[-0.2227,  0.5585, -0.1602, -0.7815,  1.4375,  0.3548,  0.5361,  0.2303,
         -0.1692,  1.3722]])
tensor([[ 0.1856,  0.1732,  0.0615,  1.9697, -0.9463]], grad_fn=<MulBackward0>)
tensor([[ 0.0928,  0.0866,  0.0308,  0.9849, -0.4732]],
       grad_fn=<AddmmBackward0>)
